
-- Add at least 3 records into each table
INSERT INTO Products (Name, Price) VALUES ('Something', 30); -- 1
INSERT INTO Products (Name, Price) VALUES ('Something Else', 40); -- 2
INSERT INTO Products (Name, Price) VALUES ('A Pencil', 0); -- 3

INSERT INTO Customers (Firstname, Lastname, CardNumber) VALUES ('John', 'Wick', 3); -- 1
INSERT INTO Customers (Firstname, Lastname, CardNumber) VALUES ('John', 'Rambo', 2); -- 2
INSERT INTO Customers (Firstname, Lastname, CardNumber) VALUES ('John', 'Smith', 1); -- 3

INSERT INTO Orders (ProductID, CustomerID) VALUES (1, 3); -- 1
INSERT INTO Orders (ProductID, CustomerID) VALUES (2, 1); -- 2
INSERT INTO Orders (ProductID, CustomerID) VALUES (3, 2); -- 3

-- Add product iPhone priced $200
INSERT INTO Products (Name, Price) VALUES ('iPhone', 200); -- 4

-- Add customer Tina Smith
INSERT INTO Customers (Firstname, Lastname, CardNumber) VALUES ('Tina', 'Smith', 12) -- 4

-- Create order for 'Tina Smith bough an iPhone'
INSERT INTO Orders (ProductID, CustomerID) VALUES (4, 4);

-- Report all orders for Tina Smith
SELECT * FROM ORDERS WHERE CustomerID = 4

-- Report all revenue generated by sales of iPhone
SELECT SUM(Price) FROM Products As p RIGHT JOIN Orders AS o ON o.ProductId = p.Id;

-- Increase price of iPhone to $250
UPDATE Products
SET Price = 250
WHERE Name = 'iPhone';